[package]
name = "janosik"
version = "0.1.1"
authors = ["hjaremko <hjaremko@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.7"
scan_fmt = "0.2.4"
wait-timeout = "0.1.5"
chrono = "0.4"
